### ISSUE TITLE
No value for is_admon_revenue

### ISSUE THREAD

**Issue by jumper423** [singular-labs/Singular-Flutter-SDK#33]
```
E/Singular(30149): BaseApi [pool-102-thread-1] - Exception: 
E/Singular(30149): No value for is_admon_revenue
E/Singular(30149): Stack trace: 
E/Singular(30149): org.json.JSONException: No value for is_admon_revenue
E/Singular(30149): 	at org.json.JSONObject.get(JSONObject.java:398)
E/Singular(30149): 	at org.json.JSONObject.getBoolean(JSONObject.java:419)
E/Singular(30149): 	at com.singular.sdk.internal.BaseApi.isAdmonEvent(BaseApi.java:80)
E/Singular(30149): 	at com.singular.sdk.internal.ApiSubmitEvent.isAdmonEvent(ApiSubmitEvent.java:29)
E/Singular(30149): 	at com.singular.sdk.internal.BatchManager$2.run(BatchManager.java:223)
E/Singular(30149): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/Singular(30149): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/Singular(30149): 	at java.lang.Thread.run(Thread.java:1012)
```

Use `singular_flutter_sdk: ^1.0.15`

**Comment by rzer** [comment]
Face with the same problem. Did you resolve the issue?

**Comment by hernanRogue** [comment]
run into the same issue , any news??

**Comment by zhouzhou94alone** [comment]
我也遇到了这个问题，
run into the same issue , any news??

**Comment by shefdanny** [comment]
log was removed.
