### ISSUE TITLE
App crashes on startup - Android

### ISSUE THREAD

**Issue by MortadhaFadhlaoui** [singular-labs/Singular-Flutter-SDK#57]
Hello sorry I can't provide too many details but the app is crashing on startup Android, please find attached the log reported on **Crashlytics**

> PlatformException(error, Attempt to invoke virtual method 'void bj.i0.L(boolean)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void bj.i0.L(boolean)' on a null object reference at aj.d.n(Singular.java:3) at zi.a.m(SingularSDK.java:13) at zi.a.onMethodCall(SingularSDK.java:366) at an.i$a.a(MethodChannel.java:18) at om.c.f(DartMessenger.java:19) at om.c.g(DartMessenger.java:42) at om.c.c(Unknown Source:0) at om.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8762) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) )

**Comment by shefdanny** [comment]
Thanks for notifying us regarding the issue. 
Fixed with released version 1.4.1

**Comment by MaxEliezerSingular** [comment]
Hi @MortadhaFadhlaoui, sorry for the long delay — this crash is no longer relevant.

It was caused by calling a Singular API (limitDataSharing) before Singular.start(), which the native Android SDK didn't guard at the time. Fixed in native Android SDK 12.7.1; the current plugin ships 12.16.0, where pre-init calls are safely ignored instead of crashing.

Please upgrade to the latest singular_flutter_sdk. If you need data sharing limited from the first session, set it on the config before init rather than calling the method afterwards.

Closing — happy to reopen if it still reproduces.
